name: Setup robostack
description: Install Zsh and pixi, then create the robostack pixi environment.

runs:
  using: composite
  steps:
    - name: Install Zsh
      shell: bash
      run: sudo apt update && sudo apt install -y zsh

    - name: Install pixi
      uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
      with:
        run-install: false

    - name: Setup robostack environment
      shell: zsh -e {0}
      run: |
        pixi init robostack
        cp ci/pixi.toml robostack/pixi.toml
        cd robostack
        pixi install
