[workspace]
name = "robostack"
description = "RoboStack ROS 2 Jazzy environment"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[target.unix.activation]
env = { RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp", ROS_SETUP_SOURCED = "1", CMAKE_GENERATOR = "Ninja" }

# Dependencies used by all environments
[dependencies]
pre-commit = "*"
python = "*"
# Compilers
compilers = "*"
cmake = "*"
pkg-config = "*"
ninja = "*"
# ROS specific tools
colcon-common-extensions = "*"
# Gazebo tools
gz-sim = "*"

[environments]
jazzy = { features = ["jazzy"] }

[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-desktop = "*"
ros-jazzy-gz-ros2-control = "*"
ros-jazzy-rmw-cyclonedds-cpp = ">=2.2.3,<3"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-ros-gz-bridge = "*"
ros-jazzy-ros-gz-sim = "*"
ros-jazzy-xacro = "*"

[feature.jazzy.tasks]
pre-commit = "cd .. && pre-commit run --all-files"
run-tests = "cd .. && colcon build && colcon test && colcon test-result --verbose"
rviz-launch = "cd .. && colcon build && bash -c 'source install/setup.bash && ros2 launch my_robot_bringup display.launch.py'"
gz-server-launch = "cd .. && colcon build && bash -c 'source install/setup.bash && ros2 launch my_robot_bringup gazebo_server.launch.py'"
rqt-graph-launch = "cd .. && colcon build && bash -c 'source install/setup.bash && ros2 run rqt_graph rqt_graph'"
