controller_manager:
  ros__parameters:
    update_rate: 100
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["chassis_to_left_wheel_joint"]
    right_wheel_names: ["chassis_to_right_wheel_joint"]
    wheel_separation: 0.25   # chassis_width (0.2) + wheel_length (0.05)
    wheel_radius: 0.1
    publish_odom: true
    publish_odom_tf: true
    odom_frame_id: odom
    base_frame_id: robot_footprint
    cmd_vel_topic: /cmd_vel
    odom_topic: /odom
