name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: zsh -e {0}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Run pre-commit hooks
        working-directory: robostack
        env:
          SKIP: check-executables-have-shebangs,docs
        run: pixi run -e jazzy pre-commit

  test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: zsh -e {0}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Run tests
        working-directory: robostack
        run: pixi run -e jazzy run-tests
