name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: zsh -e {0}

    steps:
      - uses: ./.github/actions/setup

      - name: Run pre-commit hooks
        working-directory: robostack
        run: pixi run -e jazzy pre-commit

  test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: zsh -e {0}

    steps:
      - uses: ./.github/actions/setup

      - name: Run tests
        working-directory: robostack
        run: pixi run -e jazzy run-tests
